name: Build & Release APK on main

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Change if needed

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create keystore.properties
        run: |
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Generate Release Tag Name
        id: release_tag
        run: |
          TAG_NAME="release-$(date +'%Y-%m-%d-%H%M')"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.release_tag.outputs.tag_name }}
          git push origin ${{ steps.release_tag.outputs.tag_name }}

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_tag.outputs.tag_name }}
          name: Release ${{ steps.release_tag.outputs.tag_name }}
          files: |
            app/build/outputs/apk/release/app-release.apk
            resources/**  # optional
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}