name: Build & Release APK on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create keystore.properties
        run: |
          echo "storeFile=keystore.jks" > app/keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> app/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Generate release tag
        id: tag
        run: |
          TAG_NAME="release-$(date +'%Y-%m-%d-%H%M')"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag_name }}
          git push origin ${{ steps.tag.outputs.tag_name }}

      - name: Generate changelog from commits
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          echo "Previous tag: $PREV_TAG"
          if [ -z "$PREV_TAG" ]; then
            LOG=$(git log --pretty=format:"- %s" HEAD)
          else
            LOG=$(git log --pretty=format:"- %s" "$PREV_TAG"..HEAD)
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          body: ${{ steps.changelog.outputs.log }}
          files: |
            app/build/outputs/apk/release/app-release.apk
            resources/**
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}